# Generated by Django 4.0.1 on 2022-02-10 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('name', models.CharField(default='No name', max_length=200)),
                ('price', models.FloatField(default=0.0)),
                ('stock', models.IntegerField(default=0)),
            ],
        ),
    ]
