# Generated by Django 4.0.1 on 2022-02-11 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clickoh', '0003_alter_order_date_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderdetail',
            old_name='quantitiy',
            new_name='quantity',
        ),
    ]
