# Generated by Django 4.0.1 on 2022-02-12 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clickoh', '0004_rename_quantitiy_orderdetail_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='test',
            field=models.CharField(blank=True, default='asd', max_length=200),
        ),
        migrations.AlterField(
            model_name='order',
            name='date_time',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='products',
            field=models.ManyToManyField(blank=True, through='clickoh.OrderDetail', to='clickoh.Product'),
        ),
    ]
