# Generated by Django 4.0.1 on 2022-02-12 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clickoh', '0005_order_test_alter_order_date_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='products',
            field=models.ManyToManyField(blank=True, related_name='prodsOrder', through='clickoh.OrderDetail', to='clickoh.Product'),
        ),
    ]
